In [1]:
import numpy as np
import cv2
import os
from random import shuffle
import shutil
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import tqdm

import tflearn
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression

In [2]:
path = '/Users/Kakadu/Desktop/dogs_vs_cel/MsCelebV1-Faces-Aligned.Samples'
TRAIN_DIR = '/Users/Kakadu/Desktop/dogs_vs_cel/MsAllfiles'

IMAGE_SIZE = 50


mids = next(os.walk(path))[1]
mids

['Adam Rickitt',
 'Breck Eisner',
 'Colin James',
 'Dillon',
 'Dimitra Arliss',
 'Jennifer Aniston',
 'Jennifer Lawrence',
 'John Desmond Bernal',
 'Justin Bieber',
 'Luís Fabiano',
 'Ming-Na Wen',
 'Patricia Dane',
 'Sasha Pieterse',
 'Sean Maher']

In [ ]:
new_mids = []

for i in mids:
    new_mids.append('/' + i.replace('.','/'))

new_mids

In [ ]:
"""Example of Python client calling Knowledge Graph Search API."""

import json
import urllib.request

def listic():
    
    

    api_key = 'AIzaSyBuvPmYudOVgjODmnYBrKZQrb4gaL94H6E'
    service_url = 'https://kgsearch.googleapis.com/v1/entities:search'
    
    params = {
            'limit': 10,
            'indent': True,
            'key': api_key,
            'ids':i
        }

    url = service_url + '?' + urllib.parse.urlencode(params)
    response = json.loads(urllib.request.urlopen(url).read())

    

    for element in response['itemListElement']:

        return element['result']['name']
    
        
        #return [element['result']['name'] for element in response['itemListElement']]

        

list_folder_mids = []

for i in new_mids:
    list_folder_mids.append(listic())

list_folder_mids

In [ ]:
count = 0
for name in list_folder_mids:
    if name == None:
        list_folder_mids[count] = str(count)
    count +=1
    
list_folder_mids

In [ ]:
def renaming_dirs():
    dirs = next(os.walk(path))[1]
    counter = 0
    for d in dirs:
        os.chdir(path)
        crdir = os.getcwd()
        os.rename(d, list_folder_mids[counter])
        counter = counter + 1          
        
renaming_dirs()

In [ ]:
def renaming_data():
    dirs = next(os.walk(path))[1]
    for d in dirs:
        dirPath = path  + d
        os.chdir(dirPath)     
        files = next(os.walk(dirPath))[2]        
        counter = 0       
        for f in files:         
            img_path = os.path.join(dirPath, f) 
            os.rename(img_path,(os.path.join(dirPath, d + '_' + str(counter)+'.jpg')))
            counter = counter+1
            
renaming_data()

In [ ]:
def copying_data():
    dirs = next(os.walk(path))[1]
    for d in dirs:
        dirPath = path  + d
        os.chdir(dirPath)
        files = next(os.walk(dirPath))[2]
        for f in files:
            img_path = os.path.join(dirPath, f)
            shutil.copy2(img_path, TRAIN_DIR)
            
copying_data()

In [3]:
dirs = next(os.walk(path))[1]

list_of_train_images = os.listdir(TRAIN_DIR)
list_of_train_images.remove('.DS_Store')

def creating_label(img):
    counter = 0
    for d in dirs:
        word_label = img.split('_')[0]
        if word_label == d:
            return counter
        counter = counter + 1
        
        
def creating_train_data():
    train_data = []
    for img in tqdm.tqdm(list_of_train_images):
        label = creating_label(img)
        img_path = os.path.join(TRAIN_DIR,img)
        img = cv2.imread(img_path,cv2.IMREAD_GRAYSCALE)
        img = cv2.resize(img, (IMAGE_SIZE,IMAGE_SIZE), interpolation = cv2.INTER_AREA)
        train_data.append([np.array(img),np.array([label])])
    #os.chdir(dir_for_save)
    #np.save('train_data_zooqi_large_dtst.npy', train_data)
    shuffle(train_data)
    return train_data


train_data = creating_train_data() 
train_data

100%|██████████| 1375/1375 [00:01<00:00, 711.55it/s]


[[array([[ 69,  60,  69, ...,  51,  48,  49],
         [ 63,  69,  79, ...,  51,  49,  49],
         [ 62,  71,  74, ...,  53,  51,  49],
         ..., 
         [149, 146, 142, ..., 115,  76,  80],
         [147, 149, 151, ..., 120,  95, 109],
         [152, 143, 150, ..., 133, 131, 132]], dtype=uint8), array([5])],
 [array([[  0,   0,   0, ...,   0,   0,   0],
         [  0,   0,   0, ...,   0,   0,   0],
         [  0,   0,   0, ...,   0,   0,   0],
         ..., 
         [158,  97, 166, ...,   2,   1,   3],
         [140, 112, 150, ...,  14,   8,   7],
         [156, 113, 129, ...,  32,  27,  20]], dtype=uint8), array([6])],
 [array([[ 75,  83,  61, ..., 146, 131, 107],
         [ 83,  78,  61, ..., 103, 128,  91],
         [ 91,  72,  60, ...,  72, 106,  69],
         ..., 
         [117, 101, 129, ..., 141, 148, 149],
         [183, 179, 186, ..., 128, 136, 133],
         [193, 193, 192, ..., 131, 127, 132]], dtype=uint8), array([11])],
 [array([[250, 249, 249, ...,  15,  16,  1

In [4]:
train_X = [i[0] for i in train_data]
train_X = np.array(train_X).reshape(-1,IMAGE_SIZE,IMAGE_SIZE,1)
train_y = [i[1] for i in train_data]
#train_y = np.array(train_y).reshape(-1,1)
train_y

[array([5]),
 array([6]),
 array([11]),
 array([3]),
 array([13]),
 array([5]),
 array([3]),
 array([6]),
 array([2]),
 array([0]),
 array([8]),
 array([8]),
 array([3]),
 array([11]),
 array([7]),
 array([9]),
 array([9]),
 array([6]),
 array([3]),
 array([8]),
 array([6]),
 array([4]),
 array([6]),
 array([9]),
 array([3]),
 array([4]),
 array([7]),
 array([3]),
 array([8]),
 array([4]),
 array([13]),
 array([12]),
 array([2]),
 array([6]),
 array([3]),
 array([1]),
 array([0]),
 array([10]),
 array([12]),
 array([2]),
 array([10]),
 array([0]),
 array([6]),
 array([1]),
 array([3]),
 array([5]),
 array([8]),
 array([3]),
 array([1]),
 array([10]),
 array([11]),
 array([7]),
 array([1]),
 array([2]),
 array([11]),
 array([10]),
 array([10]),
 array([2]),
 array([1]),
 array([9]),
 array([5]),
 array([6]),
 array([13]),
 array([12]),
 array([6]),
 array([6]),
 array([2]),
 array([3]),
 array([1]),
 array([3]),
 array([10]),
 array([6]),
 array([10]),
 array([6]),
 array([0]),
 array([

In [5]:
from sklearn import preprocessing
enc = preprocessing.OneHotEncoder()

train_y = enc.fit_transform(train_y).todense()
print('Shape of data is: ',train_y.shape)
print('Type of data is: ',type(train_y))
train_y

Shape of data is:  (1375, 14)
Type of data is:  <class 'numpy.matrixlib.defmatrix.matrix'>


matrix([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  1.,  0.,  0.],
        ..., 
        [ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  1.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [6]:
train_y[5]

matrix([[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.]])

In [ ]:
CNN = input_data(shape=[None, IMAGE_SIZE, IMAGE_SIZE, 1], name='input')

CNN = conv_2d(CNN, 32, 2, activation='relu')
CNN = max_pool_2d(CNN, 2)

CNN = conv_2d(CNN, 64, 2, activation='relu')
CNN = max_pool_2d(CNN, 2)

CNN = fully_connected(CNN, 1024, activation='relu')
CNN = dropout(CNN, 0.86)

CNN = fully_connected(CNN, 14, activation='linear')
CNN = regression(CNN, optimizer='adam', learning_rate=0.001, loss='categorical_crossentropy', name='targets')

model = tflearn.DNN(CNN)
model.fit({'input': train_X}, {'targets': train_y}, n_epoch=35, batch_size=128, snapshot_step=1000, show_metric=True)

In [7]:
x = tflearn.input_data(shape=[None, 50, 50, 1], name='input')

x = conv_2d(x, 64, 3, activation='relu', scope='conv1_1')
x = conv_2d(x, 64, 3, activation='relu', scope='conv1_2')
x = max_pool_2d(x, 2, strides=2, name='maxpool1')

x = conv_2d(x, 128, 3, activation='relu', scope='conv2_1')
x = conv_2d(x, 128, 3, activation='relu', scope='conv2_2')
x = max_pool_2d(x, 2, strides=2, name='maxpool2')

x = conv_2d(x, 256, 3, activation='relu', scope='conv3_1')
x = conv_2d(x, 256, 3, activation='relu', scope='conv3_2')
x = conv_2d(x, 256, 3, activation='relu', scope='conv3_3')
x = max_pool_2d(x, 2, strides=2, name='maxpool3')

x = conv_2d(x, 512, 3, activation='relu', scope='conv4_1')
x = conv_2d(x, 512, 3, activation='relu', scope='conv4_2')
x = conv_2d(x, 512, 3, activation='relu', scope='conv4_3')
x = max_pool_2d(x, 2, strides=2, name='maxpool4')

x = conv_2d(x, 512, 3, activation='relu', scope='conv5_1')
x = conv_2d(x, 512, 3, activation='relu', scope='conv5_2')
x = conv_2d(x, 512, 3, activation='relu', scope='conv5_3')
x = max_pool_2d(x, 2, strides=2, name='maxpool5')

x = fully_connected(x, 4096, activation='relu', scope='fc6')
x = dropout(x, 0.5, name='dropout1')

x = fully_connected(x, 4096, activation='relu', scope='fc7')
x = dropout(x, 0.5, name='dropout2')

x = fully_connected(x, 14, activation='softmax', scope='fc8')

x = regression(x, optimizer='adam', learning_rate=0.001, loss='categorical_crossentropy', name='targets')

model = tflearn.DNN(x)
model.fit({'input': train_X}, {'targets': train_y}, n_epoch=10, batch_size=128, snapshot_step=1000, show_metric=True)

Training Step: 109  | total loss: 2.62263 | time: 196.287s
| Adam | epoch: 010 | loss: 2.62263 - acc: 0.0932 -- iter: 1280/1375
Training Step: 110  | total loss: 2.62211 | time: 216.888s
| Adam | epoch: 010 | loss: 2.62211 - acc: 0.0925 -- iter: 1375/1375
--


In [38]:
#image_sobaka = '/Users/Kakadu/Desktop/images.jpg'

#image_sobaka = '/Users/Kakadu/Desktop/dogs_vs_cel/photo_2017-06-09_14-20-22.jpg'
image_sobaka = '/Users/Kakadu/Desktop/dogs_vs_cel/photo_2017-06-09_14-20-11.jpg'


#image_sobaka = '/Users/Kakadu/Desktop/ming-na-wen-e.jpg'
#image_sobaka = '/Users/Kakadu/Desktop/1AqND0JMZXY.jpg'


img = cv2.imread(image_sobaka,cv2.IMREAD_GRAYSCALE)
img = cv2.resize(img, (IMAGE_SIZE,IMAGE_SIZE))

test_X = img
test_X = np.array(img).reshape(-1,IMAGE_SIZE,IMAGE_SIZE,1)
test_X

array([[[[251],
         [253],
         [250],
         ..., 
         [245],
         [243],
         [243]],

        [[251],
         [251],
         [249],
         ..., 
         [243],
         [242],
         [245]],

        [[248],
         [247],
         [247],
         ..., 
         [244],
         [243],
         [248]],

        ..., 
        [[232],
         [222],
         [209],
         ..., 
         [226],
         [226],
         [223]],

        [[236],
         [229],
         [219],
         ..., 
         [226],
         [225],
         [223]],

        [[236],
         [234],
         [227],
         ..., 
         [223],
         [219],
         [221]]]], dtype=uint8)

In [39]:
model.predict(test_X)

[[0.06776732206344604,
  0.06930610537528992,
  0.06395144760608673,
  0.08050686120986938,
  0.05506611615419388,
  0.08070939779281616,
  0.08139991015195847,
  0.03691894933581352,
  0.0920528769493103,
  0.06917491555213928,
  0.08344542235136032,
  0.05896808207035065,
  0.09175101667642593,
  0.06898155063390732]]

In [40]:
model.predict_label(test_X)

array([[ 8, 12, 10,  6,  5,  3,  1,  9, 13,  0,  2, 11,  4,  7]])

In [41]:
np.argmax(model.predict(test_X)) #3 and 6 where almost together

8

In [32]:
next(os.walk(path))[1][np.argmax(model.predict(test_X))]

'Justin Bieber'

In [ ]:
#during training loss isn't going down ? why???

In [42]:
#image_sobaka = '/Users/Kakadu/Desktop/dogs_vs_cel/photo_2017-06-09_14-20-22.jpg'
#image_sobaka = '/Users/Kakadu/Desktop/dogs_vs_cel/photo_2017-06-09_14-20-11.jpg'


#image_sobaka = '/Users/Kakadu/Desktop/ming-na-wen-e.jpg'
image_sobaka = '/Users/Kakadu/Desktop/1AqND0JMZXY.jpg'


img = cv2.imread(image_sobaka,cv2.IMREAD_GRAYSCALE)
img = cv2.resize(img, (IMAGE_SIZE,IMAGE_SIZE))

test_X = img
test_X = np.array(img).reshape(-1,IMAGE_SIZE,IMAGE_SIZE,1)
test_X

array([[[[251],
         [252],
         [250],
         ..., 
         [244],
         [243],
         [244]],

        [[252],
         [250],
         [248],
         ..., 
         [243],
         [243],
         [244]],

        [[249],
         [247],
         [247],
         ..., 
         [244],
         [243],
         [247]],

        ..., 
        [[232],
         [222],
         [208],
         ..., 
         [226],
         [226],
         [224]],

        [[235],
         [229],
         [218],
         ..., 
         [227],
         [224],
         [222]],

        [[235],
         [233],
         [228],
         ..., 
         [223],
         [220],
         [221]]]], dtype=uint8)

In [46]:
model.predict(test_X)

[[0.06776731461286545,
  0.06930610537528992,
  0.06395144760608673,
  0.08050686866044998,
  0.05506611615419388,
  0.08070939779281616,
  0.08139991760253906,
  0.036918941885232925,
  0.09205286204814911,
  0.06917490810155869,
  0.08344543725252151,
  0.05896808207035065,
  0.09175100922584534,
  0.06898155063390732]]

In [43]:
model.predict_label(test_X)

array([[ 8, 12, 10,  6,  5,  3,  1,  9, 13,  0,  2, 11,  4,  7]])

In [44]:
np.argmax(model.predict(test_X)) #3 and 6 where almost together

8

In [45]:
next(os.walk(path))[1][np.argmax(model.predict(test_X))]

'Justin Bieber'